In [2]:
import torch
from torch_cluster import knn

# x = torch.Tensor([[-1, -1], [-1, 1], [1, -1], [1, 1]]).to("cuda")
# y = torch.Tensor([[-1, 0], [1, 0]]).to("cuda")
# assign_index = knn(x, y, 2)

In [3]:
a = torch.rand(580000, 3).to("cuda")
b = torch.rand(580000, 3).to("cuda")

In [7]:
assign_index = knn(a, b, 20)

In [6]:
x[assign_index[1]].view(-1, 2, 2)

tensor([[[-1., -1.],
         [-1.,  1.]],

        [[ 1., -1.],
         [ 1.,  1.]]], device='cuda:0')

In [8]:
assign_index.shape

torch.Size([2, 11600000])

In [9]:
11600000 / 20

580000.0

In [11]:
assign_index[1]

tensor([132643, 282253,  25615,  ..., 104905, 247215, 244748], device='cuda:0')

In [22]:
import torch
from pytorch3d.transforms import quaternion_to_matrix, quaternion_invert

In [4]:
rot_mat = quaternion_to_matrix(torch.randn(10, 4))

In [6]:
rot_mat.shape

torch.Size([10, 3, 3])

In [7]:
inv_rot = torch.inverse(rot_mat)

In [12]:
inv_rot.shape

torch.Size([10, 3, 3])

In [11]:
(inv_rot @ rot_mat)[0]

tensor([[ 1.0000e+00,  4.6566e-09,  0.0000e+00],
        [-9.3132e-10,  1.0000e+00, -2.9802e-08],
        [ 9.3132e-10, -5.9605e-08,  1.0000e+00]])

In [23]:
tnow_dist = torch.rand(10, 4)

In [19]:
fin = inv_rot @ tnow_dist.unsqueeze(-1)

In [20]:
fin.shape

torch.Size([10, 3, 1])

In [26]:
tnow_dist

tensor([[0.6732, 0.0541, 0.8444, 0.6895],
        [0.6078, 0.8044, 0.5129, 0.6238],
        [0.9720, 0.9525, 0.6325, 0.3721],
        [0.6097, 0.6558, 0.0319, 0.1469],
        [0.4616, 0.7769, 0.9448, 0.1961],
        [0.8593, 0.1252, 0.4825, 0.7721],
        [0.8593, 0.3796, 0.9740, 0.4721],
        [0.1689, 0.5285, 0.9798, 0.1604],
        [0.3185, 0.3067, 0.5354, 0.4452],
        [0.3145, 0.5929, 0.3398, 0.4175]])

In [25]:
(tnow_dist * quaternion_invert(tnow_dist)).sum(-1)

tensor([-0.7381, -0.9298, -0.5011, -0.0809, -1.3217, -0.1062, -0.5773, -1.2364,
        -0.4774, -0.5423])

In [27]:
quaternion_invert(tnow_dist)

tensor([[ 0.6732, -0.0541, -0.8444, -0.6895],
        [ 0.6078, -0.8044, -0.5129, -0.6238],
        [ 0.9720, -0.9525, -0.6325, -0.3721],
        [ 0.6097, -0.6558, -0.0319, -0.1469],
        [ 0.4616, -0.7769, -0.9448, -0.1961],
        [ 0.8593, -0.1252, -0.4825, -0.7721],
        [ 0.8593, -0.3796, -0.9740, -0.4721],
        [ 0.1689, -0.5285, -0.9798, -0.1604],
        [ 0.3185, -0.3067, -0.5354, -0.4452],
        [ 0.3145, -0.5929, -0.3398, -0.4175]])